# Dockerfile for Celery worker
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app

CMD ["celery", "-A", "app.tasks.process_ifc:celery_app", "worker", "--loglevel=info"]
